**Name: Syed Khizar Rayaz**

# **Import**

In [1]:
#import
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
import math
import numpy as np

import pandas as pd

from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV

# **Regression Model using Decision Tree Regressor and Multi Linear Regression**

# **Tree Regressor**

In [2]:
#changing object dtypes to int for model
!pip install category_encoders

     |████████████████████████████████| 86 kB 2.9 MB/s 


In [47]:
#import csv and display it
df = pd.read_csv('/content/house_prices_train.csv')
df.head()

Id  LotArea  OverallQual  YearBuilt RoofStyle  TotalBsmtSF CentralAir  \
0   1     8450            7       2003     Gable          856          Y   
1   2     9600            6       1976     Gable         1262          Y   
2   3    11250            7       2001     Gable          920          Y   
3   4     9550            7       1915     Gable          756          Y   
4   5    14260            8       2000     Gable         1145          Y   

   1stFlrSF  2ndFlrSF  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0       856       854         2         1             3             1   
1      1262         0         2         0             3             1   
2       920       866         2         1             3             1   
3       961       756         1         0             3             1   
4      1145      1053         2         1             4             1   

   TotRmsAbvGrd  GarageCars  GarageArea  SalePrice  
0             8           2         548     208500  
1             6           2         460     181500  
2             6           2         608     223500  
3             7           3         642     140000  
4             9           3         836     250000

In [48]:
#data details
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            1460 non-null   int64 
 1   LotArea       1460 non-null   int64 
 2   OverallQual   1460 non-null   int64 
 3   YearBuilt     1460 non-null   int64 
 4   RoofStyle     1460 non-null   object
 5   TotalBsmtSF   1460 non-null   int64 
 6   CentralAir    1460 non-null   object
 7   1stFlrSF      1460 non-null   int64 
 8   2ndFlrSF      1460 non-null   int64 
 9   FullBath      1460 non-null   int64 
 10  HalfBath      1460 non-null   int64 
 11  BedroomAbvGr  1460 non-null   int64 
 12  KitchenAbvGr  1460 non-null   int64 
 13  TotRmsAbvGrd  1460 non-null   int64 
 14  GarageCars    1460 non-null   int64 
 15  GarageArea    1460 non-null   int64 
 16  SalePrice     1460 non-null   int64 
dtypes: int64(15), object(2)
memory usage: 194.0+ KB


In [49]:
df.isna().sum()

Id              0
LotArea         0
OverallQual     0
YearBuilt       0
RoofStyle       0
TotalBsmtSF     0
CentralAir      0
1stFlrSF        0
2ndFlrSF        0
FullBath        0
HalfBath        0
BedroomAbvGr    0
KitchenAbvGr    0
TotRmsAbvGrd    0
GarageCars      0
GarageArea      0
SalePrice       0
dtype: int64

In [50]:
df.dtypes

Id               int64
LotArea          int64
OverallQual      int64
YearBuilt        int64
RoofStyle       object
TotalBsmtSF      int64
CentralAir      object
1stFlrSF         int64
2ndFlrSF         int64
FullBath         int64
HalfBath         int64
BedroomAbvGr     int64
KitchenAbvGr     int64
TotRmsAbvGrd     int64
GarageCars       int64
GarageArea       int64
SalePrice        int64
dtype: object

In [4]:
#import  encoders
import category_encoders as ce
encoder = ce.OneHotEncoder(use_cat_names=True)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
#changing object type to int
df1 = encoder.fit_transform(df)

In [6]:
#droping sale price as it is the target value
x = df1.drop(['SalePrice'],axis=1)
y = df1['SalePrice']

In [7]:
#using startified k fold for uniform division
folds = StratifiedKFold(n_splits=5)

# **Error Metrics**

# **Tree Regressor**

In [8]:
#mean sqaured error
cv = cross_val_score(DecisionTreeRegressor(), x, y, cv=5, scoring='neg_mean_squared_error')
cv

array([-1.90852489e+09, -2.06536361e+09, -1.81070279e+09, -1.46564521e+09,
       -2.31114761e+09])

In [9]:
#root mean square
cv = cross_val_score(DecisionTreeRegressor(), x, y, cv=5, scoring='neg_root_mean_squared_error')
cv

array([-45769.21514272, -46035.05510958, -42088.38574256, -39290.02416296,
       -50991.44287797])

In [10]:
#absolute error
cv = cross_val_score(DecisionTreeRegressor(), x, y, cv=5, scoring='neg_mean_absolute_error')
cv

array([-30788.54109589, -31458.96575342, -27517.93150685, -24789.71232877,
       -34055.52054795])

# **Multi Linear Regression**

In [51]:
#mean sqaured error
cv = cross_val_score(LinearRegression(), x, y, cv=5, scoring='neg_mean_squared_error')
cv

array([-9.45292873e+08, -1.32492298e+09, -1.55383475e+09, -1.03020107e+09,
       -2.51408550e+09])

In [12]:
#root mean square
cv = cross_val_score(LinearRegression(), x, y, cv=5, scoring='neg_root_mean_squared_error')
cv

array([-30745.61551542, -36399.49148297, -39418.7106898 , -32096.74541939,
       -50140.65719644])

In [13]:
#absolute error
cv = cross_val_score(LinearRegression(), x, y, cv=5, scoring='neg_mean_absolute_error')
cv

array([-22960.99422891, -23149.89849027, -24109.51160092, -22350.24914187,
       -26432.62892418])

# **Accuracy Comparison**

In [14]:
#accuracy of decision tree which is low as compare to multi linear regression accuracy
cv = cross_val_score(DecisionTreeRegressor(),x,y)
np.average(cv)

0.684151894308665

In [15]:
cv = cross_val_score(LinearRegression(),x,y)
np.average(cv)

0.7688302715670936

# **Hyper Parameters**

In [45]:
#trying different sets of parameters and finding its impact on score
model_params = {
    'decision_tree': {
        'model': DecisionTreeRegressor(),
        'params' : {
          'max_depth': [2,4,6,8,10,12],
          'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
          'splitter':['best', 'random'],
        }
    },
    'linear_regression' : {
        'model': LinearRegression(),
        'params': {
            'normalize':[True,False],
            'fit_intercept':[True,False]
        }
    }
}

In [46]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(x,y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df2 = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df2
#both model have accuracy of more than 70%, both models are performing good.

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pi

model  best_score  \
0      decision_tree    0.740261   
1  linear_regression    0.768830   

                                         best_params  
0  {'criterion': 'friedman_mse', 'max_depth': 6, ...  
1        {'fit_intercept': True, 'normalize': False}